<h3>This new page is generated by CRM/Eventpermissions/Page/MyEvents.php</h3>

<table>
{foreach from=$events key=eventId item=eventTitle}
  <tr>
    <td>{$eventTitle.title}</td>
    <td>{$eventTitle.links}</td>
  </tr>
{/foreach}
</table>
